### ISSUE TITLE
Privacy error when visiting website

### ISSUE THREAD

**Issue by sgango** [Imperial-College-Data-Science-Society/icdss#3]
![image](https://user-images.githubusercontent.com/25332542/91557665-cc154400-e92c-11ea-9fd0-b4d77efa09ea.png)

Probable fix here: https://medium.com/@monarchwadia/github-pages-setting-up-www-subdomain-with-ssl-https-aca9eca371d6

**Comment by sytan98** [comment]
Yup this has been an issue that we faced. We have corrected it and it should work fine now. Do let me know if the issue still persists:)

**Comment by sgango** [comment]
Seems to be all sorted now 👍
